### ISSUE TITLE
Question: Performance 

### ISSUE THREAD

**Issue by Muetze42** [ghostzero/tmi#13]
Can anyone say how the performance is with PHP 8.2 (or already PHP 8.3) compared to the Node.Js version? Preferably even with many clients?

**Comment by ghostzero** [comment]
It depends more on your rate limit's at twitch, overall never seen any performance issues with it. I use this client in environments with 100.000 concurrent channels in combination with ghostzero/tmi-cluster.

**Comment by Muetze42** [comment]
OK, thanks for the answer. 

Then I'll give it a try. I'm currently passing the requests from Node.js to a Laravel app anyway. Of course, it would be practical to have everything under one roof.

I miss the disconnected event that exists in the Node.Js script. Will you add this?

```js
client.on('disconnected', (reason) => {
    // Handle disconnect
});
```
